# Generated by Django 2.2.5 on 2019-10-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_entrymodel_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrymodel',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='h1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='h2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='h3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='h4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='h5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='text2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='text3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='text4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='text5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
