# Generated by Django 2.2.5 on 2019-10-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20191016_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='h2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='h3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='h4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='h5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='recommend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='text4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='text5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
