# Generated by Django 2.2.5 on 2019-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testNumber', models.IntegerField(unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
