# Generated by Django 2.1.5 on 2020-04-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='testNumber',
            new_name='testnumber',
        ),
    ]
